### ISSUE TITLE
Add rolling for archive files

### ISSUE THREAD

**Issue by alex0598** [cocowalla/serilog-sinks-file-archive#10] opened 2022-03-08 01:19 UTC
It should also be possible to keep a maximum number of files in the archive folder.

**Comment by cocowalla** [comment] 2022-03-09 10:24
Are you asking for something different than #1, or can I close this as a duplicate?

**Comment by cocowalla** [comment] 2024-09-10 10:29
Closing, assuming duplicate of #1

**Closed as completed by cocowalla** 2024-09-10 10:29 UTC
